repos:
  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [ "--ignore=W503,W605,D107,D102,I100,D100,D103,F401,I201" ]
        additional_dependencies:
          - flake8-import-order
          - flake8-import-single==0.1.5
          - flake8-builtins
          - flake8-docstrings
          - flake8-rst-docstrings
          - pydocstyle<4.0.0
          - pygments