version: "3.10"

services:
  webapp:
    restart: always
    container_name: webapp
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    command: bash -c "alembic upgrade head && uvicorn src.core:app --reload --host 0.0.0.0"
    networks:
      - db_net
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6374:6379"
    env_file:
      - ./.env
    networks:
      - db_net

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: "python3 -m celery -A src.tasks.tasks:celery worker -l info"
    depends_on:
      - webapp
      - redis
      - db
    restart: on-failure
    networks:
      - db_net

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env
    networks:
      - db_net

  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - webapp
    ports:
      - "8082:80"
    volumes:
      - ./nginx:/etc/nginx/nginx
    networks:
      - db_net

volumes:
  postgres_data:
networks:
  db_net:
