"""Create tables

Revision ID: d95a6f1bf756
Revises: 
Create Date: 2024-01-05 16:38:33.948403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd95a6f1bf756'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=256), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('vacancy',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=256), nullable=False),
                    sa.Column('salary', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('worker',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=256), nullable=False),
                    sa.Column('last_name', sa.String(length=256), nullable=False),
                    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resume',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('worker_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=256), nullable=False),
                    sa.Column('salary', sa.Integer(), nullable=True),
                    sa.Column('specialization', sa.String(length=256), nullable=False),
                    sa.Column('employment',
                              sa.Enum('full_time', 'part_time', 'internship', 'project_work', name='employment'),
                              nullable=False),
                    sa.Column('experience', sa.Integer(), nullable=False),
                    sa.Column('work_type', sa.Enum('remote', 'office', 'combined', name='worktype'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vacancy_reply',
                    sa.Column('resume_id', sa.Integer(), nullable=False),
                    sa.Column('vacancy_id', sa.Integer(), nullable=False),
                    sa.Column('cover_letter', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('resume_id', 'vacancy_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_reply')
    op.drop_table('resume')
    op.drop_table('worker')
    op.drop_table('vacancy')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
